server:
   address: localhost
   port: 9800
logging:
   config: classpath:log4j2.xml

spring:
   dataSource:
      master:
         driverClassName: com.mysql.jdbc.Driver
         url: jdbc:mysql://172.16.0.246:3306/quizzes?useUnicode=true&characterEncoding=utf-8
         username: caiqiu
         password: Caiqiu502
         initialSize: 20
         minIdle: 5
         maxActive: 30
         maxWait: 30000
         removeAbandoned: true
         removeAbandonedTimeoutMillis: 300000
         defaultAutoCommit: false
         timeBetweenEvictionRunsMillis: 60000
         minEvictableIdleTimeMillis: 300000
         validationQuery: SELECT 1
         testWhileIdle: true
         connectionInitSql: set names utf8mb4
      slave:
         driverClassName: com.mysql.jdbc.Driver
         url: jdbc:mysql://172.16.0.246:3306/quizzes?useUnicode=true&characterEncoding=utf-8
         username: caiqiu
         password: Caiqiu502
         initialSize: 20
         minIdle: 5
         maxActive: 30
         maxWait: 30000
         removeAbandoned: true
         removeAbandonedTimeoutMillis: 300000
         defaultAutoCommit: false
         timeBetweenEvictionRunsMillis: 60000
         minEvictableIdleTimeMillis: 300000
         validationQuery: SELECT 1
         testWhileIdle: true
         connectionInitSql: set names utf8mb4
